import { KeyFunc } from "./types";

export const Esc = { code: "KC_ESC" };
export const A = { code: "KC_A" };
export const B = { code: "KC_B" };
export const C = { code: "KC_C" };
export const D = { code: "KC_D" };
export const E = { code: "KC_E" };
export const F = { code: "KC_F" };
export const G = { code: "KC_G" };
export const H = { code: "KC_H" };
export const I = { code: "KC_I" };
export const J = { code: "KC_J" };
export const K = { code: "KC_K" };
export const L = { code: "KC_L" };
export const M = { code: "KC_M" };
export const N = { code: "KC_N" };
export const O = { code: "KC_O" };
export const P = { code: "KC_P" };
export const Q = { code: "KC_Q" };
export const R = { code: "KC_R" };
export const S = { code: "KC_S" };
export const T = { code: "KC_T" };
export const U = { code: "KC_U" };
export const V = { code: "KC_V" };
export const W = { code: "KC_W" };
export const X = { code: "KC_X" };
export const Y = { code: "KC_Y" };
export const Z = { code: "KC_Z" };
export const K_0 = { code: "KC_0", label: ["0", ")"] };
export const K_1 = { code: "KC_1", label: ["1", "!"] };
export const K_2 = { code: "KC_2", label: ["2", "@"] };
export const K_3 = { code: "KC_3", label: ["3", "#"] };
export const K_4 = { code: "KC_4", label: ["4", "$"] };
export const K_5 = { code: "KC_5", label: ["5", "%"] };
export const K_6 = { code: "KC_6", label: ["6", "^"] };
export const K_7 = { code: "KC_7", label: ["7", "&"] };
export const K_8 = { code: "KC_8", label: ["8", "*"] };
export const K_9 = { code: "KC_9", label: ["9", "("] };
export const F1 = { code: "KC_F1" };
export const F2 = { code: "KC_F2" };
export const F3 = { code: "KC_F3" };
export const F4 = { code: "KC_F4" };
export const F5 = { code: "KC_F5" };
export const F6 = { code: "KC_F6" };
export const F7 = { code: "KC_F7" };
export const F8 = { code: "KC_F8" };
export const F9 = { code: "KC_F9" };
export const F10 = { code: "KC_F10" };
export const F11 = { code: "KC_F11" };
export const F12 = { code: "KC_F12" };
export const F13 = { code: "KC_F13" };
export const F14 = { code: "KC_F14" };
export const F15 = { code: "KC_F15" };
export const F16 = { code: "KC_F16" };
export const F17 = { code: "KC_F17" };
export const F18 = { code: "KC_F18" };
export const F19 = { code: "KC_F19" };
export const F20 = { code: "KC_F20" };
export const F21 = { code: "KC_F21" };
export const F22 = { code: "KC_F22" };
export const F23 = { code: "KC_F23" };
export const F24 = { code: "KC_F24" };
export const P0 = { code: "KC_P0" };
export const P1 = { code: "KC_P1" };
export const P2 = { code: "KC_P2" };
export const P3 = { code: "KC_P3" };
export const P4 = { code: "KC_P4" };
export const P5 = { code: "KC_P5" };
export const P6 = { code: "KC_P6" };
export const P7 = { code: "KC_P7" };
export const P8 = { code: "KC_P8" };
export const P9 = { code: "KC_P9" };
export const Tab = { code: "KC_TAB" };
export const Tilde = { code: "KC_GRV", label: ["`", "~"], cn: "lg" };
export const LShift = { code: "KC_LSFT", label: ["Shift"] };
export const RShift = { code: "KC_RSFT", label: ["Shift"] };
export const LCtrl = { code: "KC_LCTL", label: ["Ctrl"] };
export const RCtrl = { code: "KC_RCTL", label: ["Ctrl"] };
export const Super = { code: "KC_LGUI", label: ["Super"] };
export const Alt = { code: "KC_LALT", label: ["Alt"] };
export const Space = { code: "KC_SPC", label: [""] };
export const Up = { code: "KC_UP", label: ["&#8593;"], cn: "lg" };
export const Down = { code: "KC_DOWN", label: ["&#8595;"], cn: "lg" };
export const Left = { code: "KC_LEFT", label: ["&#8592;"], cn: "lg" };
export const Right = { code: "KC_RIGHT", label: ["&#8594;"], cn: "lg" };
export const Enter = { code: "KC_ENT", label: ["Return"] };
export const Backslash = { code: "KC_BSLS", label: ["\\", "|"] };
export const Backspace = { code: "KC_BSPC", label: ["Backspace"] };
export const Minus = { code: "KC_MINS", label: ["-", "_"] };
export const Equals = { code: "KC_EQL", label: ["=", "+"] };
export const LBracket = { code: "KC_LBRC", label: ["[", "{"] };
export const RBracket = { code: "KC_RBRC", label: ["]", "}"] };
export const Semicolon = { code: "KC_SCLN", label: [";", ":"] };
export const Quote = { code: "KC_QUOT", label: ["'", '"'] };
export const Comma = { code: "KC_COMM", label: [",", "<"] };
export const Period = { code: "KC_DOT", label: [".", ">"] };
export const Slash = { code: "KC_SLSH", label: ["/", "?"] };
export const Delete = { code: "KC_DEL", label: ["Delete"] };
export const Tns = { code: "KC_TRNS", label: [""] };
export const Reset = { code: "RESET", label: ["RESET"] };
export const MNext = { code: "KC_MNXT", label: ["Next", "track"] };
export const MPrev = { code: "KC_MPRV", label: ["Prev", "track"] };
export const MPP = { code: "KC_MPLY", label: ["Play", "Pause"] };
export const Caps = { code: "KC_CAPS", label: ["Caps Lock"] };
export const Print = { code: "KC_PSCR", label: ["Print"] };
export const Home = { code: "KC_HOME" };
export const Ins = { code: "KC_INS" };
export const End = { code: "KC_END" };
export const PgUp = { code: "KC_PGUP", label: ["PgUp"] };
export const PgDn = { code: "KC_PGDN", label: ["PgDn"] };
export const VolUp = { code: "KC_VOLU", label: ["Vol+"] };
export const VolDn = { code: "KC_VOLD", label: ["Vol-"] };
export const BrUp = { code: "KC_BRIU", label: ["Bri+"] };
export const BrDn = { code: "KC_BRID", label: ["Bri-"] };
export const PSlash = { code: "KC_PSLS" };
export const PAsterisk = { code: "KC_PAST" };
export const PMinus = { code: "KC_PMNS" };

export const Custom: KeyFunc = (c) => ({ code: `CU_${c}`, label: [c] });
export const Str: KeyFunc = (c, l) => ({ code: `CU_${c}`, label: [c], str: l });
export const Fn: KeyFunc = (l) => ({
  code: `MO(LYR_${l.toUpperCase()}_FN)`,
  label: ["Fn"],
});
export const Layer: KeyFunc = (l) => ({
  code: `DF(LYR_${l.toUpperCase()})`,
  label: [`${l} layer`],
});
